"""add token usage columns to call_session

Revision ID: 34fc389ea6e5
Revises: 82ffd7b03b9b
Create Date: 2026-04-19 17:12:05.440838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '34fc389ea6e5'
down_revision: Union[str, Sequence[str], None] = '82ffd7b03b9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('call_session', sa.Column('input_audio_tokens', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('call_session', sa.Column('output_audio_tokens', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('call_session', sa.Column('input_text_tokens', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('call_session', sa.Column('output_text_tokens', sa.Integer(), nullable=False, server_default='0'))
    op.alter_column('call_session', 'input_audio_tokens', server_default=None)
    op.alter_column('call_session', 'output_audio_tokens', server_default=None)
    op.alter_column('call_session', 'input_text_tokens', server_default=None)
    op.alter_column('call_session', 'output_text_tokens', server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('call_session', 'output_text_tokens')
    op.drop_column('call_session', 'input_text_tokens')
    op.drop_column('call_session', 'output_audio_tokens')
    op.drop_column('call_session', 'input_audio_tokens')
    # ### end Alembic commands ###
