"""add webhook_url to user

Revision ID: 3f88cf860e4c
Revises: a2d650c33ef2
Create Date: 2026-04-19 17:57:18.314557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3f88cf860e4c'
down_revision: Union[str, Sequence[str], None] = 'a2d650c33ef2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('webhook_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'webhook_url')
    # ### end Alembic commands ###
