"""widen token counters to bigint and cascade file user_id

Revision ID: 42f1228c7ba6
Revises: a251f22a133e
Create Date: 2026-04-21 12:36:25.612464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '42f1228c7ba6'
down_revision: Union[str, Sequence[str], None] = 'a251f22a133e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('call_session', 'input_audio_tokens',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('call_session', 'output_audio_tokens',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('call_session', 'input_text_tokens',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('call_session', 'output_text_tokens',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.drop_constraint(op.f('file_user_id_fkey'), 'file', type_='foreignkey')
    op.create_foreign_key('file_user_id_fkey', 'file', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('file_user_id_fkey', 'file', type_='foreignkey')
    op.create_foreign_key(op.f('file_user_id_fkey'), 'file', 'user', ['user_id'], ['id'])
    op.alter_column('call_session', 'output_text_tokens',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('call_session', 'input_text_tokens',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('call_session', 'output_audio_tokens',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('call_session', 'input_audio_tokens',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
