"""add is_active to user

Revision ID: 706b6921ee97
Revises: 9857314f4bf8
Create Date: 2026-04-23 09:47:03.006792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '706b6921ee97'
down_revision: Union[str, Sequence[str], None] = '9857314f4bf8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add with server_default so existing rows backfill to TRUE, then drop the default.
    op.add_column(
        'user',
        sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.text('true')),
    )
    op.alter_column('user', 'is_active', server_default=None)
    op.create_index(op.f('ix_user_is_active'), 'user', ['is_active'], unique=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_is_active'), table_name='user')
    op.drop_column('user', 'is_active')
    # ### end Alembic commands ###
