from app.core.exceptions import BaseServiceError


class TaskNotFoundError(BaseServiceError): ...


class TaskNotCancellableError(BaseServiceError): ...


class InvalidTaskDataError(BaseServiceError): ...


class TaskNotEditableError(BaseServiceError): ...


class PhoneRateLimitExceededError(BaseServiceError): ...
